### ISSUE TITLE
Feature: When click review should redirect to the movie/show page

### ISSUE THREAD

**Issue by vmnog** [plotwist-app/plotwist#115]
In home page we have the popular reviews but we can only click on the movie page, for the user its natural to try to click on the review but currently nothing happens.

My suggestion is: When click review should redirect to the movie/show page with the review centered in screen and with some emphasis on it.

Example:

1. Click on the review:

![image](https://uploads.linear.app/7dd38012-c4e1-4993-a62d-9537a9402ed0/2d716b33-79db-4d48-a39b-e1567896cfe0/3b6b89ac-9ac6-4c33-9388-b9efcee96c37?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdkZDM4MDEyLWM0ZTEtNDk5My1hNjJkLTk1MzdhOTQwMmVkMC8yZDcxNmIzMy03OWRiLTRkNDgtYTM5Yi1lMTU2Nzg5NmNmZTAvM2I2Yjg5YWMtOWFjNi00YzMzLTkzODgtYjllZmNlZTk2YzM3IiwiaWF0IjoxNzE1MDk3Njc0LCJleHAiOjMzMjg1NjU3Njc0fQ.ggR6jnlwyWjIBEBzBDhsyTQ8mTh1Nf5szCqCBDg1VE8)

1. User is redirect to show page with the review clicked with emphasis (suggestion of emphasis color can change)

![image](https://uploads.linear.app/7dd38012-c4e1-4993-a62d-9537a9402ed0/00f11e9a-f1af-40ac-bcbb-836783979770/499ae0fc-0f73-4889-88da-431b086e95cc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdkZDM4MDEyLWM0ZTEtNDk5My1hNjJkLTk1MzdhOTQwMmVkMC8wMGYxMWU5YS1mMWFmLTQwYWMtYmNiYi04MzY3ODM5Nzk3NzAvNDk5YWUwZmMtMGY3My00ODg5LTg4ZGEtNDMxYjA4NmU5NWNjIiwiaWF0IjoxNzE1MDk3Njc0LCJleHAiOjMzMjg1NjU3Njc0fQ.zu4sBGZKlYR_cP3YITVAEhsKLsaLRmkkwTArTQ8vjao)

**Comment by lui7henrique** [comment]
LGTM!
