### ISSUE TITLE
Feat: Should be able to check who liked your review comment

### ISSUE THREAD

**Issue by vmnog** [plotwist-app/plotwist#116]
Today we only show the counter of how many likes are in the review, but would be a good addition to list the usernames and being able to navigate to their profile pages or following them from the like listage.
![image](https://github.com/plotwist-app/plotwist/assets/43258815/5ab7131a-d49a-45c7-851b-635fe4f6a5b0)

My suggestion is to make some float modal like instagram:
![image](https://github.com/plotwist-app/plotwist/assets/43258815/b6442281-0a1c-41cb-b950-6298a2d55d2a)

**Comment by lui7henrique** [comment]
LGTM!
