### ISSUE TITLE
Bug: Review disappears when changing language

### ISSUE THREAD

**Issue by Suburbanno** [plotwist-app/plotwist#228]
When I change the language of the site, my reviews disappear, they are only available in the language the site was in when the review was created.

Portuguese:
![image](https://github.com/user-attachments/assets/15ae1b5b-84a9-4f26-967a-b4bd5e9c0dc7)

English:

![image](https://github.com/user-attachments/assets/ce6e29ae-3ff4-43ef-a6b4-802e77068c3e)

**Comment by Vicentesan** [comment]
Hey @Suburbanno!

This is not a bug, but rather a feature we initially developed for the website. The idea was to improve the user experience by excluding reviews in languages like Japanese for users in the US, for example. However, we understand the importance of giving users more control over their experience, so we’re planning to add a toggle option in the user profile settings. This will allow users to choose whether or not they want to see foreign reviews.

What do you think about this approach?

Best regards,
Vicente Sanchez

**Comment by Suburbanno** [comment]
> Hey @Suburbanno!
> 
> This is not a bug, but rather a feature we initially developed for the website. The idea was to improve the user experience by excluding reviews in languages like Japanese for users in the US, for example. However, we understand the importance of giving users more control over their experience, so we’re planning to add a toggle option in the user profile settings. This will allow users to choose whether or not they want to see foreign reviews.
> 
> What do you think about this approach?
> 
> Best regards, Vicente Sanchez

I think it's interesting that the user has the option to choose. I particularly like reading reviews in other languages.
