### ISSUE TITLE
Feature: About page

### ISSUE THREAD

**Issue by Suburbanno** [plotwist-app/plotwist#237]
An about page to talk a little about the project, contacts, information about features, roadmap, etc.

ex:

![image](https://github.com/user-attachments/assets/0f77c17b-8d9c-41b8-9ae9-aa3f5a2f69a4)
![image](https://github.com/user-attachments/assets/84f3b3a0-bfc9-44c3-8693-abc516049ac2)

**Comment by Vicentesan** [comment]
@lui7henrique Se conseguir fazer o texto ja faço essa pagina
