### ISSUE TITLE
[bug] I signed up for plotwist pro but I'm still on the free plan

### ISSUE THREAD

**Issue by Suburbanno** [plotwist-app/plotwist#291]
The subscription was completed, but I'm still on the free plan, without releasing more lists, without a pro badge, etc.

![image](https://github.com/user-attachments/assets/6ae6f594-e356-4de5-be44-d77b3262fe5f)
![image](https://github.com/user-attachments/assets/5dafdf37-99db-46d8-90d5-edc03692701e)

I should also receive an email with proof of purchase and that didn't happen, I only have the proof from my bank

**Comment by Vicentesan** [comment]
Hey there, we'll investigate it now!
