### ISSUE TITLE
Bug: Returning error 500 when viewing a list

### ISSUE THREAD

**Issue by Suburbanno** [plotwist-app/plotwist#299]
https://plotwist.app/pt-BR/lists/7dbb2b92-e40a-4082-a639-94f15aeff6cc

![image](https://github.com/user-attachments/assets/63ddfa45-fcf0-4ab2-aeb6-91daef8ee830)

**Comment by lui7henrique** [comment]
Thanks for reporting this issue and the details! I'll look to that right now.

**Comment by lui7henrique** [comment]
@Suburbanno, We just fixed it, if you can test it, we would greatly appreciate it.

**Comment by Suburbanno** [comment]
@lui7henrique fixed, ty!

**Comment by Suburbanno** [comment]
@lui7henrique  this list: https://plotwist.app/pt-BR/lists/64f29b3f-9443-4539-be01-76a07cb949ee
