### ISSUE TITLE
Feature: Improve Indication of Assigned Reviews

### ISSUE THREAD

**Issue by lui7henrique** [plotwist-app/plotwist#356]
**Title:** Improve Indication of Assigned Reviews

**Description:**
Currently, when a user assigns a review, the button only displays “Reviewed,” which can go unnoticed. This may cause users to click multiple times or forget that they have already submitted a review.

**Suggestion:**
- Change the star icon on the button to turn yellow when a review has been assigned.

**Benefits:**
- Provides a clear visual indication that the review has been submitted.
- Prevents duplicate clicks and enhances the user experience.

![image](https://github.com/user-attachments/assets/c1e76a04-8ffa-4e85-899d-ad0507dafcab)

**Comment by Suburbanno** [comment]
I didn't have this problem, as reading was enough for visual feedback, but it's very valid.

**Comment by Vicentesan** [comment]
do u guys prefer the filled or only stroked one?
![image](https://github.com/user-attachments/assets/e08a1ab2-76b8-4bd3-8132-f1c7545eb92d)
![image](https://github.com/user-attachments/assets/ecba6c6d-3893-42b4-8a6a-96cc89ea5f2b)

**Comment by Suburbanno** [comment]
@Vicentesan filled

**Comment by Vicentesan** [comment]
okay, i'll submit a PR

**Comment by Vicentesan** [comment]
> okay, i'll submit a PR

sorry for the delay, just submited the PR. i was having some trouble with my pgp keys hahahhaha
