### ISSUE TITLE
Bug: Filter by streaming provider does not work as expected

### ISSUE THREAD

**Issue by Suburbanno** [plotwist-app/plotwist#375]
When I filter by science fiction, regardless of date range, and select a few streaming providers, only 1 item is returned to me. Shouldn't it return all items in that genre from all selected providers?

![image](https://github.com/user-attachments/assets/43d8617a-d710-48a4-b834-0f1c23a2970b)
![image](https://github.com/user-attachments/assets/94b58c66-dc73-4a22-bad8-9d7413c74ce1)

The filter only considers whether the item is present in all providers.

So if Item X is present in 4 different providers that are selected in the filter, it will be shown

![image](https://github.com/user-attachments/assets/4372dfb5-92f1-44af-8678-bdd2399c9714)

If I put "animation" and "science fiction" as genre and in the providers select netflix and amazon, the result is empty

![image](https://github.com/user-attachments/assets/22524d3c-6ef7-429c-b8a3-8bfbdeed68e5)
![image](https://github.com/user-attachments/assets/d0dbb6c5-b11b-4465-86f8-780080e83bc0)

**Comment by lui7henrique** [comment]
Previously we used this **"AND"** filter, so it would basically filter results for films and series that were on **ALL** selected streaming services, but there have been other complaints about this and it will be changed to **"OR"**, that is, if they are on one of the selected streams will be brought.

**Comment by lui7henrique** [comment]
Fixed!
