### ISSUE TITLE
Feature: User should be able to navigate to premium related features

### ISSUE THREAD

**Issue by vmnog** [plotwist-app/plotwist#97]
![image](https://github.com/status-451/plotwist/assets/43258815/f4700bc5-af17-471e-89ca-a2b262dba47a)

For example: If user clicks on Endless Lists card it should redirect to lists pages so the user can play with the new premium feature. 

https://plotwist.app/en-US/thank-you -> https://plotwist.app/en-US/lists

This should be applied to all the other features.

**Comment by lui7henrique** [comment]
LGTM! I'll move this issue for currently Iterate.
